{% set name = "protobuf" %}
{% set version = "3.5.1" %}
{% set sha256 = "826425182ee43990731217b917c5c3ea7190cfda141af4869e6d4ad9085a740f" %}

package:
  name: {{ name }}-cpp
  version: {{ version }}

source:
  url: https://github.com/google/protobuf/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    #######################################################
    # Apply patches for pre-C++11 compilers.              #
    #                                                     #
    # xref: https://github.com/google/protobuf/pull/4124  #
    #######################################################
    - PR_4124.patch

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - toolchain
    - git                # [win]
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - zlib 1.2.11
    - python             # [win]
    - unzip              # [unix]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format."

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - hajapy
